services:
  db:
    image: mysql:8
    container_name: multas-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: multasdb
    ports:
      - "3306:3306"
    volumes:
      - dados-mysql:/var/lib/mysql

  app:
    build: .
    container_name: multas-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db

volumes:
  - dados-mysql:/var/lib/mysql
  - ./init.sql:/docker-entrypoint-initdb.d/init.sql